INSERT INTO PRICE(TOOL_TYPE, DAILY_CHARGE, WEEKDAY_CHARGE, WEEKEND_CHARGE, HOLIDAY_CHARGE)
  VALUES
      ('Ladder', 1.99, true, true, false),
      ('Chainsaw', 1.49, true, false, true),
      ('Jackhammer', 2.99, true, false, false);
  
INSERT INTO TOOL(PRICE_ID, TOOL_CODE, TOOL_TYPE, BRAND)
  SELECT ID AS PRICE_ID, 'CHNS', 'Chainsaw', 'Stihl' FROM PRICE WHERE TOOL_TYPE = 'Chainsaw';
  
INSERT INTO TOOL(PRICE_ID, TOOL_CODE, TOOL_TYPE, BRAND)
  SELECT ID AS PRICE_ID, 'LADW', 'Ladder', 'Werner' FROM PRICE WHERE TOOL_TYPE = 'Ladder';
  
INSERT INTO TOOL(PRICE_ID, TOOL_CODE, TOOL_TYPE, BRAND)
  SELECT ID AS PRICE_ID, 'JAKD', 'Jackhammer', 'DeWalt' FROM PRICE WHERE TOOL_TYPE = 'Jackhammer';
  
INSERT INTO TOOL(PRICE_ID, TOOL_CODE, TOOL_TYPE, BRAND)
  SELECT ID AS PRICE_ID, 'JAKR', 'Jackhammer', 'Ridgid' FROM PRICE WHERE TOOL_TYPE = 'Jackhammer';