
name: Branch Workflow

on: 
  push:
    branches-ignore:
      - 'main'
      - 'release*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build
      run: mvn -B clean package -DskipTests

    - name: Test
      run: mvn -B test

    