
name: Cloudformation Workflow

on:
  push:
    # branches:
    #   - 'main'
    # paths:
    #   - 'tool-rentals-infra.yml'

permissions:
  id-token: write
jobs:
  deploy_cloudformation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}
          aws-region: us-east-1

      - name: Deploy cloudformation stack
        run: aws cloudformation deploy --template-file tool-rentals-infra.yml --stack-name tool-rentals-stack --capabilities CAPABILITY_IAM

