
name: Main Workflow

on: 
  push:
    paths:
      - 'src/**'
      - 'Dockerfile'

jobs:
  publish-artifact:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      - name: Maven deploy
        run: mvn -B clean deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-docker:
    runs-on: ubuntu-latest
    needs: [publish-artifact]
    env:
      DOCKER_REPO: citc31/tool-rentals

    steps:
      - uses: actions/checkout@v4

      - name: Dockerhub login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Docker image build
        run: docker build -t $DOCKER_REPO:latest .

      - name: Docker image publish
        run: docker push $DOCKER_REPO