
name: Java CI with Maven

on: push

env:
  USER_NAME: user-name

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: List directory
      run: | 
        echo "User name $USER_NAME"
        ls -al
